# Generated by Django 4.1.3 on 2023-02-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('observation', models.CharField(max_length=150)),
                ('route', models.CharField(max_length=500)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisitesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
                ('prerequisites', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.prerequisites')),
            ],
        ),
    ]
